name: super_store_e_commerce_flutter
description: "Flutter E-Commerce App"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  url_launcher: ^6.3.1
  google_fonts: ^6.1.0
  http: ^1.2.2
  icons_plus: ^5.0.0
  shared_preferences: ^2.3.3
  email_validator: ^3.0.0
  shimmer: ^3.0.0
  form_validator: ^2.1.1
  image_picker: ^1.1.2
  form_builder_image_picker: ^4.1.0
  dropdown_search: ^6.0.1
  quickalert: ^1.1.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  rounded_background_text: ^0.5.0
  avatar_glow: ^3.0.1
  dio: ^5.7.0
  permission_handler: ^11.3.1
  calendar_date_picker2: ^1.1.8
  open_file: ^3.5.10
  rename_app: ^1.6.1
  fl_chart: ^0.69.2
  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^18.0.1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  archive: ^3.6.1
  win32: ^5.5.3
# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
